server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111
    url: jdbc:mysql://127.0.0.1:3306/sell_dining?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 119.3.180.22
    port: 6379
  resources:
    static-locations: file:G:\JavaSource\dining\src\main\resources\static\,classpath:/static/
  mvc:
    static-path-pattern: /**
mybatis:
  mapper-locations: classpath:com.order.dining.dao.mappers/*Mapper.xml
  type-aliases-package: com.order.dining.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

wechat:
  mpAppId: wx4a51c29bfe2ee580
  mpAppSecret: 2ba2b15193247c0e28fff1b4fa985fa1
  mchId: todo
  mchKey: todo
  keyPath: todo
  notifyUrl: todo