server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:// :3306/order_dining?characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:com.order.dining.dao.mappers/*Mapper.xml
  type-aliases-package: com.order.dining.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql