server:
  port: 8080
  servlet:
    context-path: /dining
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111
    url: jdbc:mysql://127.0.0.1:3306/order_dining?characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:mappers/*Mappers.xml
  type-aliases-package: com.order.dining.domain