package com.order.dining.dao.domain;

import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

@Data
public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_name
     *
     * @mbg.generated
     */
    private String buyerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_phone
     *
     * @mbg.generated
     */
    private String buyerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_address
     *
     * @mbg.generated
     */
    private String buyerAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.buyer_openid
     *
     * @mbg.generated
     */
    private String buyerOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_amount
     *
     * @mbg.generated
     */
    private BigDecimal orderAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbg.generated
     */
    private Byte orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_status
     *
     * @mbg.generated
     */
    private Byte payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

}