package com.order.dining.dao.mappers;

import com.order.dining.beans.form.SearchForm;
import com.order.dining.dao.domain.PayOrder;

import java.util.List;

public interface PayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insert(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insertSelective(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    PayOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayOrder record);

    /**
     * 分页查找用户订单信息
     *
     * @param openId
     * @return
     */
    List<PayOrder> selectByBuyerOpenId(String openId);

    /**
     * 分页查找用户订单信息
     *
     * @return
     */
    List<PayOrder> selectAll();

    List<PayOrder> searchByForm(SearchForm searchForm);
}