package com.order.dining.dao.mappers;

import com.order.dining.dao.domain.SellerInfo;
import org.apache.ibatis.annotations.Param;

public interface SellerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated
     */
    int insert(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated
     */
    int insertSelective(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated
     */
    SellerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SellerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seller_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SellerInfo record);

    SellerInfo selectByUsernameAndPwd(@Param("username") String username, @Param("pwd") String pwd);

    SellerInfo selectByPrimaryUsername(String username);
}